# Generated by Django 4.0.4 on 2022-04-14 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='full_name',
            new_name='username',
        ),
    ]
