# Generated by Django 4.0.4 on 2022-04-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_portfolio_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='template',
            field=models.PositiveSmallIntegerField(choices=[(1, 11), (2, 22)], default=1, verbose_name='Выбор шаблона'),
        ),
    ]
