# Generated by Django 4.0.4 on 2022-04-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_alter_portfolio_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='template',
            field=models.PositiveSmallIntegerField(choices=[(11, 'radio-1'), (22, 'radio-2')], default=1, verbose_name='Выбор шаблона'),
        ),
    ]
