# Generated by Django 4.0.4 on 2022-04-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_alter_portfolio_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='template',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default=0, max_length=1, verbose_name='Выбор шаблона'),
        ),
    ]
