# Generated by Django 4.0.4 on 2022-04-27 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_alter_portfolio_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='career',
            field=models.CharField(choices=[('1', 'Программист'), ('2', 'Дизайнер'), ('3', 'Специалист')], default=0, max_length=1, verbose_name='Род деятельности'),
        ),
    ]
