# Generated by Django 4.0.4 on 2022-05-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_alter_portfolio_career'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, verbose_name='Обратная связь')),
                ('is_readed', models.BooleanField(default=True, verbose_name='Прочитано')),
            ],
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='career',
            field=models.CharField(choices=[('Программист', 'Программист'), ('Дизайнер', 'Дизайнер'), ('Специалист', 'Специалист')], default=0, max_length=64, verbose_name='Род деятельности'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='experience',
            field=models.CharField(choices=[('Нет опыта', 'Нет опыта'), ('От 1 года до 3 лет', 'От 1 года до 3 лет'), ('От 3 до 6 лет ', 'От 3 до 6 лет '), ('Более 6 лет', 'Более 6 лет')], default=0, max_length=100, verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='template',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default=1, max_length=1, verbose_name='Выбор шаблона'),
        ),
    ]
