# Generated by Django 4.0.4 on 2022-05-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_feedback_alter_portfolio_career_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='is_readed',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
    ]
